enum ShowcaseUniformKind { float, color, colorArray }

class ShowcaseUniformSpec {
  const ShowcaseUniformSpec.float(this.name)
    : kind = ShowcaseUniformKind.float,
      capacity = 0;

  const ShowcaseUniformSpec.color(this.name)
    : kind = ShowcaseUniformKind.color,
      capacity = 0;

  const ShowcaseUniformSpec.colorArray(this.name, this.capacity)
    : kind = ShowcaseUniformKind.colorArray;

  final String name;
  final ShowcaseUniformKind kind;
  final int capacity;

  String get label {
    final raw = name.startsWith('u_') ? name.substring(2) : name;
    final words = raw
        .replaceAllMapped(
          RegExp(r'([a-z0-9])([A-Z])'),
          (match) => '${match[1]} ${match[2]}',
        )
        .replaceAll('_', ' ')
        .split(' ');
    return words
        .where((word) => word.isNotEmpty)
        .map((word) => word[0].toUpperCase() + word.substring(1))
        .join(' ');
  }
}

const showcaseUniforms = <String, List<ShowcaseUniformSpec>>{
  'color-panels': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.colorArray('u_colors', 7),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.float('u_density'),
    ShowcaseUniformSpec.float('u_angle1'),
    ShowcaseUniformSpec.float('u_angle2'),
    ShowcaseUniformSpec.float('u_length'),
    ShowcaseUniformSpec.float('u_edges'),
    ShowcaseUniformSpec.float('u_blur'),
    ShowcaseUniformSpec.float('u_fadeIn'),
    ShowcaseUniformSpec.float('u_fadeOut'),
    ShowcaseUniformSpec.float('u_gradient'),
  ],
  'dithering': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.float('u_pxSize'),
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.color('u_colorFront'),
    ShowcaseUniformSpec.float('u_shape'),
    ShowcaseUniformSpec.float('u_type'),
  ],
  'dot-grid': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.color('u_colorFill'),
    ShowcaseUniformSpec.color('u_colorStroke'),
    ShowcaseUniformSpec.float('u_dotSize'),
    ShowcaseUniformSpec.float('u_gapX'),
    ShowcaseUniformSpec.float('u_gapY'),
    ShowcaseUniformSpec.float('u_strokeWidth'),
    ShowcaseUniformSpec.float('u_sizeRange'),
    ShowcaseUniformSpec.float('u_opacityRange'),
    ShowcaseUniformSpec.float('u_shape'),
  ],
  'dot-orbit': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.colorArray('u_colors', 10),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_stepsPerColor'),
    ShowcaseUniformSpec.float('u_size'),
    ShowcaseUniformSpec.float('u_sizeRange'),
    ShowcaseUniformSpec.float('u_spreading'),
  ],
  'fluted-glass': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.color('u_colorShadow'),
    ShowcaseUniformSpec.color('u_colorHighlight'),
    ShowcaseUniformSpec.float('u_size'),
    ShowcaseUniformSpec.float('u_shadows'),
    ShowcaseUniformSpec.float('u_angle'),
    ShowcaseUniformSpec.float('u_stretch'),
    ShowcaseUniformSpec.float('u_shape'),
    ShowcaseUniformSpec.float('u_distortion'),
    ShowcaseUniformSpec.float('u_highlights'),
    ShowcaseUniformSpec.float('u_distortionShape'),
    ShowcaseUniformSpec.float('u_shift'),
    ShowcaseUniformSpec.float('u_blur'),
    ShowcaseUniformSpec.float('u_edges'),
    ShowcaseUniformSpec.float('u_marginLeft'),
    ShowcaseUniformSpec.float('u_marginRight'),
    ShowcaseUniformSpec.float('u_marginTop'),
    ShowcaseUniformSpec.float('u_marginBottom'),
    ShowcaseUniformSpec.float('u_grainMixer'),
    ShowcaseUniformSpec.float('u_grainOverlay'),
  ],
  'gem-smoke': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.colorArray('u_colors', 6),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.color('u_colorInner'),
    ShowcaseUniformSpec.float('u_innerDistortion'),
    ShowcaseUniformSpec.float('u_outerDistortion'),
    ShowcaseUniformSpec.float('u_outerGlow'),
    ShowcaseUniformSpec.float('u_innerGlow'),
    ShowcaseUniformSpec.float('u_offset'),
    ShowcaseUniformSpec.float('u_angle'),
    ShowcaseUniformSpec.float('u_size'),
    ShowcaseUniformSpec.float('u_shape'),
    ShowcaseUniformSpec.float('u_isImage'),
  ],
  'god-rays': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.color('u_colorBloom'),
    ShowcaseUniformSpec.colorArray('u_colors', 5),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_density'),
    ShowcaseUniformSpec.float('u_spotty'),
    ShowcaseUniformSpec.float('u_midSize'),
    ShowcaseUniformSpec.float('u_midIntensity'),
    ShowcaseUniformSpec.float('u_intensity'),
    ShowcaseUniformSpec.float('u_bloom'),
  ],
  'grain-gradient': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.colorArray('u_colors', 7),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_softness'),
    ShowcaseUniformSpec.float('u_intensity'),
    ShowcaseUniformSpec.float('u_noise'),
    ShowcaseUniformSpec.float('u_shape'),
  ],
  'halftone-cmyk': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.color('u_colorC'),
    ShowcaseUniformSpec.color('u_colorM'),
    ShowcaseUniformSpec.color('u_colorY'),
    ShowcaseUniformSpec.color('u_colorK'),
    ShowcaseUniformSpec.float('u_size'),
    ShowcaseUniformSpec.float('u_contrast'),
    ShowcaseUniformSpec.float('u_grainSize'),
    ShowcaseUniformSpec.float('u_grainMixer'),
    ShowcaseUniformSpec.float('u_grainOverlay'),
    ShowcaseUniformSpec.float('u_gridNoise'),
    ShowcaseUniformSpec.float('u_softness'),
    ShowcaseUniformSpec.float('u_floodC'),
    ShowcaseUniformSpec.float('u_floodM'),
    ShowcaseUniformSpec.float('u_floodY'),
    ShowcaseUniformSpec.float('u_floodK'),
    ShowcaseUniformSpec.float('u_gainC'),
    ShowcaseUniformSpec.float('u_gainM'),
    ShowcaseUniformSpec.float('u_gainY'),
    ShowcaseUniformSpec.float('u_gainK'),
    ShowcaseUniformSpec.float('u_type'),
  ],
  'halftone-dots': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorFront'),
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.float('u_radius'),
    ShowcaseUniformSpec.float('u_contrast'),
    ShowcaseUniformSpec.float('u_size'),
    ShowcaseUniformSpec.float('u_grainMixer'),
    ShowcaseUniformSpec.float('u_grainOverlay'),
    ShowcaseUniformSpec.float('u_grainSize'),
    ShowcaseUniformSpec.float('u_grid'),
    ShowcaseUniformSpec.float('u_originalColors'),
    ShowcaseUniformSpec.float('u_inverted'),
    ShowcaseUniformSpec.float('u_type'),
  ],
  'heatmap': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.colorArray('u_colors', 10),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_angle'),
    ShowcaseUniformSpec.float('u_noise'),
    ShowcaseUniformSpec.float('u_innerGlow'),
    ShowcaseUniformSpec.float('u_outerGlow'),
    ShowcaseUniformSpec.float('u_contour'),
  ],
  'image-dithering': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorFront'),
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.color('u_colorHighlight'),
    ShowcaseUniformSpec.float('u_type'),
    ShowcaseUniformSpec.float('u_pxSize'),
    ShowcaseUniformSpec.float('u_originalColors'),
    ShowcaseUniformSpec.float('u_inverted'),
    ShowcaseUniformSpec.float('u_colorSteps'),
  ],
  'liquid-metal': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.color('u_colorTint'),
    ShowcaseUniformSpec.float('u_softness'),
    ShowcaseUniformSpec.float('u_repetition'),
    ShowcaseUniformSpec.float('u_shiftRed'),
    ShowcaseUniformSpec.float('u_shiftBlue'),
    ShowcaseUniformSpec.float('u_distortion'),
    ShowcaseUniformSpec.float('u_contour'),
    ShowcaseUniformSpec.float('u_angle'),
    ShowcaseUniformSpec.float('u_shape'),
    ShowcaseUniformSpec.float('u_isImage'),
  ],
  'mesh-gradient': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.colorArray('u_colors', 10),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_distortion'),
    ShowcaseUniformSpec.float('u_swirl'),
    ShowcaseUniformSpec.float('u_grainMixer'),
    ShowcaseUniformSpec.float('u_grainOverlay'),
  ],
  'metaballs': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.colorArray('u_colors', 8),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_size'),
    ShowcaseUniformSpec.float('u_count'),
  ],
  'neuro-noise': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorFront'),
    ShowcaseUniformSpec.color('u_colorMid'),
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.float('u_brightness'),
    ShowcaseUniformSpec.float('u_contrast'),
  ],
  'paper-texture': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorFront'),
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.float('u_contrast'),
    ShowcaseUniformSpec.float('u_roughness'),
    ShowcaseUniformSpec.float('u_fiber'),
    ShowcaseUniformSpec.float('u_fiberSize'),
    ShowcaseUniformSpec.float('u_crumples'),
    ShowcaseUniformSpec.float('u_crumpleSize'),
    ShowcaseUniformSpec.float('u_folds'),
    ShowcaseUniformSpec.float('u_foldCount'),
    ShowcaseUniformSpec.float('u_drops'),
    ShowcaseUniformSpec.float('u_seed'),
    ShowcaseUniformSpec.float('u_fade'),
  ],
  'perlin-noise': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorFront'),
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.float('u_proportion'),
    ShowcaseUniformSpec.float('u_softness'),
    ShowcaseUniformSpec.float('u_octaveCount'),
    ShowcaseUniformSpec.float('u_persistence'),
    ShowcaseUniformSpec.float('u_lacunarity'),
  ],
  'pulsing-border': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.colorArray('u_colors', 5),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_roundness'),
    ShowcaseUniformSpec.float('u_thickness'),
    ShowcaseUniformSpec.float('u_marginLeft'),
    ShowcaseUniformSpec.float('u_marginRight'),
    ShowcaseUniformSpec.float('u_marginTop'),
    ShowcaseUniformSpec.float('u_marginBottom'),
    ShowcaseUniformSpec.float('u_aspectRatio'),
    ShowcaseUniformSpec.float('u_softness'),
    ShowcaseUniformSpec.float('u_intensity'),
    ShowcaseUniformSpec.float('u_bloom'),
    ShowcaseUniformSpec.float('u_spotSize'),
    ShowcaseUniformSpec.float('u_spots'),
    ShowcaseUniformSpec.float('u_pulse'),
    ShowcaseUniformSpec.float('u_smoke'),
    ShowcaseUniformSpec.float('u_smokeSize'),
  ],
  'simplex-noise': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.colorArray('u_colors', 10),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_stepsPerColor'),
    ShowcaseUniformSpec.float('u_softness'),
  ],
  'smoke-ring': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.colorArray('u_colors', 10),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_thickness'),
    ShowcaseUniformSpec.float('u_radius'),
    ShowcaseUniformSpec.float('u_innerShape'),
    ShowcaseUniformSpec.float('u_noiseScale'),
    ShowcaseUniformSpec.float('u_noiseIterations'),
  ],
  'spiral': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.color('u_colorFront'),
    ShowcaseUniformSpec.float('u_density'),
    ShowcaseUniformSpec.float('u_distortion'),
    ShowcaseUniformSpec.float('u_strokeWidth'),
    ShowcaseUniformSpec.float('u_strokeCap'),
    ShowcaseUniformSpec.float('u_strokeTaper'),
    ShowcaseUniformSpec.float('u_noise'),
    ShowcaseUniformSpec.float('u_noiseFrequency'),
    ShowcaseUniformSpec.float('u_softness'),
  ],
  'static-mesh-gradient': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.colorArray('u_colors', 10),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_positions'),
    ShowcaseUniformSpec.float('u_waveX'),
    ShowcaseUniformSpec.float('u_waveXShift'),
    ShowcaseUniformSpec.float('u_waveY'),
    ShowcaseUniformSpec.float('u_waveYShift'),
    ShowcaseUniformSpec.float('u_mixing'),
    ShowcaseUniformSpec.float('u_grainMixer'),
    ShowcaseUniformSpec.float('u_grainOverlay'),
  ],
  'static-radial-gradient': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.colorArray('u_colors', 10),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_radius'),
    ShowcaseUniformSpec.float('u_focalDistance'),
    ShowcaseUniformSpec.float('u_focalAngle'),
    ShowcaseUniformSpec.float('u_falloff'),
    ShowcaseUniformSpec.float('u_mixing'),
    ShowcaseUniformSpec.float('u_distortion'),
    ShowcaseUniformSpec.float('u_distortionShift'),
    ShowcaseUniformSpec.float('u_distortionFreq'),
    ShowcaseUniformSpec.float('u_grainMixer'),
    ShowcaseUniformSpec.float('u_grainOverlay'),
  ],
  'swirl': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.colorArray('u_colors', 10),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_bandCount'),
    ShowcaseUniformSpec.float('u_twist'),
    ShowcaseUniformSpec.float('u_center'),
    ShowcaseUniformSpec.float('u_proportion'),
    ShowcaseUniformSpec.float('u_softness'),
    ShowcaseUniformSpec.float('u_noise'),
    ShowcaseUniformSpec.float('u_noiseFrequency'),
  ],
  'voronoi': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.colorArray('u_colors', 5),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_stepsPerColor'),
    ShowcaseUniformSpec.color('u_colorGlow'),
    ShowcaseUniformSpec.color('u_colorGap'),
    ShowcaseUniformSpec.float('u_distortion'),
    ShowcaseUniformSpec.float('u_gap'),
    ShowcaseUniformSpec.float('u_glow'),
  ],
  'warp': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.colorArray('u_colors', 10),
    ShowcaseUniformSpec.float('u_colorsCount'),
    ShowcaseUniformSpec.float('u_proportion'),
    ShowcaseUniformSpec.float('u_softness'),
    ShowcaseUniformSpec.float('u_shape'),
    ShowcaseUniformSpec.float('u_shapeScale'),
    ShowcaseUniformSpec.float('u_distortion'),
    ShowcaseUniformSpec.float('u_swirl'),
    ShowcaseUniformSpec.float('u_swirlIterations'),
  ],
  'water': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.color('u_colorHighlight'),
    ShowcaseUniformSpec.float('u_highlights'),
    ShowcaseUniformSpec.float('u_layering'),
    ShowcaseUniformSpec.float('u_edges'),
    ShowcaseUniformSpec.float('u_caustic'),
    ShowcaseUniformSpec.float('u_waves'),
    ShowcaseUniformSpec.float('u_size'),
  ],
  'waves': <ShowcaseUniformSpec>[
    ShowcaseUniformSpec.color('u_colorFront'),
    ShowcaseUniformSpec.color('u_colorBack'),
    ShowcaseUniformSpec.float('u_shape'),
    ShowcaseUniformSpec.float('u_frequency'),
    ShowcaseUniformSpec.float('u_amplitude'),
    ShowcaseUniformSpec.float('u_spacing'),
    ShowcaseUniformSpec.float('u_proportion'),
    ShowcaseUniformSpec.float('u_softness'),
  ],
};
